icon: mdi:shield-home
name: Security
cards:
  - type: "custom:compact-custom-header"   
    main_config: false
    background: 'rgba(150, 150, 150, 0.2)'
    menu: show
    options: show
    voice: show
    notifications: clock
    clock_format: '24'
    clock_date: true
    date_locale: en-gb
    disable: false 


  - type: alarm-panel
    name: Larm
    entity: alarm_control_panel.alarm

  - type: vertical-stack
    cards:

      - type: entities
        show_header_toggle: false
        title: Dörrar
        entities:
          - entity: binary_sensor.maindoor
            name: Entré
            secondary_info: last-changed
          - entity: binary_sensor.backdoor
            name: Vardagsrum
            secondary_info: last-changed
          - entity: binary_sensor.backdoor
            name: Kök
            secondary_info: last-changed
          - entity: binary_sensor.backdoor
            name: Tvättstuga
            secondary_info: last-changed
          - type: divider
          - entity: binary_sensor.backdoor
            name: Barnrum
            secondary_info: last-changed
          - entity: binary_sensor.backdoor
            name: Sovrum
            secondary_info: last-changed
          - type: divider
          - entity: binary_sensor.backdoor
            icon: mdi:garage
            name: Garage
            secondary_info: last-changed    



  - type: vertical-stack
    cards:

      - type: entities
        title: Rörelsesensorer
        show_header_toggle: false
        entities:
          - entity: binary_sensor.hallway
            name: Hall
            secondary_info: last-changed
          - entity: binary_sensor.kitchen
            name: Kök
            secondary_info: last-changed
          - entity: binary_sensor.kitchen
            name: Tvättstuga
            secondary_info: last-changed
          - entity: binary_sensor.kitchen
            name: Vardagsrum
            secondary_info: last-changed

      - type: entities
        title: Vattensensorer
        show_header_toggle: false
        entities:
          - entity: binary_sensor.hallway
            name: Hall
            secondary_info: last-changed
