homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include includes/customize.yaml
  customize_glob: !include includes/customize_glob.yaml
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
ssdp:
zeroconf:

# Fail2ban
logger:
  default: critical
  logs:
    homeassistant.components.http.ban: warning

# Themes
frontend: !include includes/frontend.yaml

# GPS Locator
owntracks:
  max_gps_accuracy: 100
  events_only: false
  waypoints: true

lovelace:
  mode: yaml
  
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret base_url

# Discover some devices automatically
discovery:

# HA Community STore
hacs:
  token: !secret hacs_token

# Sensors
sensor:
  # Weather prediction
  - platform: yr

  - platform: time_date
    display_options:
      - 'time'
      - 'date'

recorder:
  purge_keep_days: 5
  purge_interval: 1
  include:
    entities:
      - binary_sensor.backdoor
      - binary_sensor.maindoor
      - calendar.familj
      - calendar.sophamtningplast
      - calendar.sophamtningavfall
      - device_tracker.jonas_jonass9
      - device_tracker.jonas_s9
      - device_tracker.malin_s9
      - sensor.jonas
      - sensor.malin

  exclude:
    domains:
      - updater
      - camera
      - media_player
      - sun
      - zone
      - group
      - sensor
      - binary_sensor
      - calendar
      - input_boolean
      - lights
      - device_tracker

# Text to speech
tts:
  - platform: google_translate

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

device_tracker: !include includes/device_tracker.yaml
group: !include includes/groups.yaml
script: !include includes/scripts.yaml
switch: !include includes/switches.yaml
zone: !include includes/zones.yaml
input_boolean: !include includes/input_boolean.yaml
python_script:
