homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include includes/customize.yaml
  customize_glob: !include includes/customize_glob.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - '/config'

default_config:
ssdp:
zeroconf:
discovery:

lovelace:
  mode: yaml

http:
  base_url: !secret base_url

hacs:
  token: !secret hacs_token

# Fail2ban
logger:
  default: critical
  logs:
    homeassistant.components.http.ban: warning

sensor:
  - platform: yr
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_jonas

notify:
  - name: jonas
    platform: telegram
    chat_id: !secret telegram_jonas

tts:
  - platform: google_translate

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

frontend: !include includes/frontend.yaml
history: !include includes/history.yaml
recorder: !include includes/recorder.yaml
device_tracker: !include includes/device_tracker.yaml
group: !include includes/groups.yaml
script: !include includes/scripts.yaml
switch: !include includes/switches.yaml
zone: !include includes/zones.yaml
input_boolean: !include includes/input_boolean.yaml
shell_command: !include includes/shell_command.yaml
python_script:

# GPS Locator
# owntracks:
#   max_gps_accuracy: 100
#   events_only: false
#   waypoints: true
