title: !secret title_address

resources:
#  - url: /community_plugin/compact-custom-header/compact-custom-header.js
#    type: module
  - url: /local/custom-lovelace/popup-card.js
    type: js
  - url: /community_plugin/weather-card/weather-card.js
    type: module 
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
  - url: /community_plugin/calendar-card/calendar-card.js
    type: js
  - url: /community_plugin/simple-weather-card/simple-weather-card-bundle.js
    type: module
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js


# cch:
#   main_config: true
#   background: 'rgba(0,0,0,0)'
#   menu: show
#   options: show
#   voice: show
#   notifications: clock
#   clock_format: '24'
#   clock_date: true
#   date_locale: sv-SE
#   disable: false

background: center / cover no-repeat url("/local/backgrounds/background_20.png") fixed
views:
  - !include lovelace/00_homeview.yaml    
  - !include lovelace/10_security.yaml   
  - !include lovelace/20_weather.yaml   
  - !include lovelace/70_plants.yaml   
  - !include lovelace/80_servers.yaml   
  - !include lovelace/90_automations.yaml 