automation:
  - alias: Inside Lights - Some lights on Baby sleeps
    trigger:
      - platform: state
        entity_id: input_boolean.inside_lights
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.baby_sleepmode
        state: "on"
    action:
      - service: hue.hue_activate_scene
        data:
          group_name: "Vardagsbelysning"
          scene_name: "Evening_nobedroom"
  
  - alias: Inside Lights - All lights on Baby awake
    trigger:
      - platform: state
        entity_id: input_boolean.inside_lights
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.baby_sleepmode
        state: "off"
    action:
      - service: hue.hue_activate_scene
        data:
          group_name: "Vardagsbelysning"
          scene_name: "Evening_all"
  
  
  - alias: Inside Lights - All lights off 
    trigger:
      - platform: state
        entity_id: input_boolean.inside_lights
        to: "off"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.guestmode
          state: "off"
        - condition: state
          entity_id: input_boolean.nightlights_malin
          state: "off"
    action:
      - service: light.turn_off
        data:
          entity_id: group.all_lights

  
  - alias: Inside Lights - All lights off except guestroom
    trigger:
      - platform: state
        entity_id: input_boolean.inside_lights
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.guestmode
        state: "on"
    action:
      - service: light.turn_off
        data:
          entity_id: group.all_lights_guest


  - alias: Inside Lights - All lights off nightlight on
    trigger:
      - platform: state
        entity_id: input_boolean.inside_lights
        to: "off"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.nightlights_malin
          state: "on"
        - condition: state
          entity_id: input_boolean.baby_sleepmode
          state: "on"
        - condition: state
          entity_id: input_boolean.guestmode
          state: "off"
    action:
      - service: hue.hue_activate_scene
        data:
          group_name: "Vardagsbelysning"
          scene_name: "Redlight_malin"

  - alias: Inside Lights - Turn on lights around sunset
    trigger:
      - platform: sun
        event: sunset
        offset: "-01:00:00"
    condition:
      - condition: state
        entity_id: sensor.family
        state: "home"
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.inside_lights


  - alias: Motion Sensors Lights On
    trigger:
      - platform: state
        entity_id: binary_sensor.upstairs_move, binary_sensor.hallway_move, binary_sensor.kitchen_move
        to: 'on'         
    condition:
      condition: and
      conditions:
        - condition: time
          after: "21:30"
          before: "10:00"
        - condition: sun
          before: sunrise
        - condition: state
          entity_id: input_boolean.inside_lights
          state: "off"
    action:
      - service: light.turn_on
        data:
          entity_id: 
            - light.koksfonster
            - light.vardagsrumsfonster
            - light.overvaning_hall
          brightness: 20

  - alias: Motion Sensors Lights Off 
    trigger:
      platform: state
      entity_id: binary_sensor.upstairs_move, binary_sensor.hallway_move, binary_sensor.kitchen_move
      to: 'off'
      for: '00:05:00'
    condition:
      condition: and
      conditions:
        - condition: time
          after: "21:30"
        - condition: sun
          before: sunrise
        - condition: state
          entity_id: input_boolean.inside_lights
          state: "off"
    action:
      - service: light.turn_off
        data:
          entity_id: group.diaperchange

  - alias: Arriving home
    trigger:
      platform: state
      entity_id: device_tracker.presence_jonas, device_tracker.presence_malin
      to: "Just arrived"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: "below_horizon"
        - condition: state
          entity_id: input_boolean.inside_lights
          state: "off"
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.inside_lights

  - alias: Leaving home
    trigger:
      platform: state
      entity_id: device_tracker.presence_jonas, device_tracker.presence_malin
      to: "Away"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.family
          state: "not_home"
        - condition: state
          entity_id: input_boolean.inside_lights
          state: "on"
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.inside_lights
      - service: media_player.media_pause
        data:
          entity_id: 
            - media_player.vardagsrum
            - media_player.kok
            - media_player.overvaning

  - alias: Buggy IKEA-light
    trigger:
      - platform: state
        entity_id: light.kontor_hylla
        to: "on"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.inside_lights
          state: "off"
        - condition: state
          entity_id: light.Kontorsfonster
          state: "off"

    action:
      - service: light.turn_off
        data:
          entity_id: light.kontor_hylla