automation:
  - alias: 'Set Theme to Midnight'
    initial_state: 'on'
    trigger:
    - platform: homeassistant
      event: start
    action:
    - service: frontend.set_theme
      data:
        name: midnightclear