group:
  family:
    name: Family
    view: no
    entities:
      - device_tracker.jonas_jonass9
      - device_tracker.jonas_s9
      - device_tracker.malin_s9


sensor:
## Presence-sensor for mainview     
  - platform: template
    sensors:
        
      jonas:
        friendly_name: "Jonas"
        value_template: >-
          {% if is_state('device_tracker.jonas_jonass9', 'home') %}
            Hemma
          {% elif is_state('device_tracker.jonas_jonass9', 'jonaswork') %}
            Telia
          {% elif is_state('device_tracker.jonas_jonass9', 'maxi') %}
            Maxi
          {% elif is_state('device_tracker.jonas_s9', 'home') %}
            Hemma
          {% else %}
            Borta
          {% endif %}
        entity_picture_template: >-
          {% if is_state('device_tracker.jonas_jonass9', 'home') %}
            /local/profiles/jonas.jpg
          {% elif is_state('device_tracker.jonas_s9', 'home') %}
            /local/profiles/jonas.jpg
          {% else %}
            /local/profiles/jonasbw.jpg   
          {% endif %}
        icon_template: >-
          {% if is_state('device_tracker.jonas_jonass9', 'jonaswork') %}
            mdi:briefcase
          {% elif is_state('device_tracker.jonas_jonass9', 'maxi') %}
            mdi:cart
          {% else %}
            mdi:walk
          {% endif %}
          
      malin:
        friendly_name: "Malin"
        value_template: >-
          {% if is_state('device_tracker.malin_s9', 'home') %}
            Hemma
          {% elif is_state('device_tracker.malin_s9', 'malinwork') %}
            EY
          {% elif is_state('device_tracker.malin_s9', 'maxi') %}
            Maxi
          {% else %}
            Borta
          {% endif %}
        entity_picture_template: >-
          {% if is_state('device_tracker.malin_s9', 'home') %}
            /local/profiles/malin.jpg
          {% else %}
            /local/profiles/malinbw.jpg          
          {% endif %}
        icon_template: >-
          {% if is_state('device_tracker.malin_s9', 'Maxi') %}
            mdi:cart
          {% else %}
            mdi:walk
          {% endif %}

  - platform: template
    sensors:
      s9_battery:
        friendly_name: 'S9 Battery'
        value_template: '{{ states.device_tracker.jonas_jonass9.attributes.battery_level | round }}'
        unit_of_measurement: '%'



